export const hotelTypes = [
  "Budget",
  "Luxury",
  "Boutique",
  "Ski Resort",
  "Business",
  "Family",
  "Romantic",
  "Wedding Destination",
  "Hiking Resort",
  "Cabin",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Mountain View",
  "Pilgrimage stay",
  "Weekend Party",
]